version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SSH_PRIVATE_KEY: |
          -----BEGIN RSA PRIVATE KEY-----
          b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABAeOCHyvf
          yq086PGH3ZnANEAAAAEAAAAAEAAAIXAAAAB3NzaC1yc2EAAAADAQABAAACAQC+Ai3ByH6y
          GlEFgduxQ6lKOmr3JX6xG+itWP//ezhW05OhUzXCN/j8/IKrhXz5xYXITPW3MspH+JiPfO
          eGITfZm+VnW6LIgai9KycLcqE5ifen6F0jNnB/znJbdjVXDUICzWkCZ9oxIp3iPdAhchKl
          F+gdY13E1bN7eXX/ugWCwH/vmNarm7QWLuM9Oggo2x3woCdewy30FQ2CBl5kDg+BA0njs+
          9ip4QC4oK5ovZrNmxw3xL+iNeV+3/cYPQGkDcFP/9QnQPRxnbubaotEknbOi5KNtgujMgJ
          amD0e59jh2VoekgjntssVRAZ7bEtIKIzVr2PRibNmiXPKWQkJEOmnMiTgw+WOarqJQmhlU
          VMbTKhiOjgQiW3rUEziageeCHfyrnAaDQfhLx490bVd+2ff7FfPHo6PAU1dIrDI8sAfaWO
          AOLlD/vP7JMmx8JdtHPV6oEyMqSTsqEyJfp4Qv9AqOivHR6cPSr04l73rg6waLXpcT6bkT
          CurAnGdwZwYAn3htZSIkI6wFf4OpxUmmLErsjsXEqTl8KE/VkJcpj9rkSvldwQ3NJQ+evc
          COMc6DRpzoX2czNk5ELXLehlN/yoUKV7lYpluHxO/JIay2cw/oe2Terql22+yfukPT/TbF
          e0o6dsSpWDG3sqLefy+DFXqAC8XxaZ92OluOMAcr627QAAB1CJOqIHFWOE6mOfoLDBpumz
          8CPJzENeI3Mwb1kkbfXwrZ/vThzZl03lphEON/t/ssBMRWKj+ORvu40g1E1l/vaQxcyeU3
          IGSM+qoE9ZJJdhEw8z1qIjVWg7EooVdUMMS4mKVZD4jXdCvPpSw00Bb4D4atCPWrfMFdl/
          zzhOjVNj560OXmVGrXVjg88k4etWaUzEPeq471RmXS0HwME/TSqOV6qwoipoQO9UWEFe5v
          ntvcTxXmnlZVaovgMJNixKIhB1/JplVG3pKWMtDwL2T+QS+4N/Jf1MSVRRi7zhzkOJUrSd
          y37n7LZVQNUKbE+2e9CNDhZ4hy+qY3Ip/AVn6atEdUrfhwypmr5k2uGwm4M+kggAeunECU
          EP9cTHmIRHLvW4RhtyGFn33RPEE1mv14PoJBdZmcrCq3e2MfciJSpdP2Z4R9CsEquVjffY
          059kW8lKmSKRUVunwC3XgFQ8uBHjZs3FvpIA0rTRSjYna8j45Cc1dsKAJ3WH5p8v6IEJeO
          jo1nbZL192wJd800cS1ttZaTHkXsR/LXP0X7Zz/mEOilaYEJ8KxHWF6JA39FPYK6RPzAhi
          kflyX9zeV5qDB7dUVt6G5IBghqIEjI7bVH1uN5P3VGgMusUOsFSmR8PlYwNI4rcdofk72p
          yOYJqqxz5ipA4sEReccJx+C0hlgjezd2OQt/Mf5+1Bh+FlzYKqq6Swg7cHaGqrmOFlykfZ
          rMG1E8x99LEg3RHFQSk2S5UUb5FDzUsMGvAnk4CGtsm8RWTV5oOglGhB8HEGWPp8H8tnkQ
          dLemAZKnc9pQ+zIfGH1+NpV755VPZF3gkbmnmQoRfJZIDj/lfYIB2zD5B9F+QTtW2PsplM
          Dya69ZXtXk4j/9X0dJQVqcuZUvtqk83fOWT2VrcmfVnRMYc+tiL2qDHohhJNi/vpbp9owo
          vl5AOD580OxqHF4+ySuXa6Y8R93xB/UXxpXT34agYN4Lzv+TqiZgOiyx7VKuXIrVPVfRfA
          FxThRROXMwTz98WRrmU97MFbXfNFrlEbLuCgp+3+6bsBH2ZDxPJqCYXtrpg46J0c8qV4l/
          IFM2dO5cNu0WUBC+bWUAg+qeKaeOXyLOpxG6WfsTyi+jJX0NMPUlNAyikwvOv/3VpaqCcN
          LQUrMYNccx/qKBjd3qgQ9XF3L7VYQ6K7GZQlBjLUDuWkuHtDBnzcOR4CrKx9nDujTz8zIn
          yBKRDLv8poNO+50c7u6ozIMwCFS9jBpYS3oc5z7QYrLrGSJnnAtn8GedA/TqZkt+ShR+3p
          h2iHSYMJjByRf5FZlwukY0aBqPX5A+gFakiqzhJmZ9pa7/p+SVs8OWEvtBwCpthHJfXdob
          4A+tc/iObZLuKo2tLPRi9DK2iS/P5+Z42LDn7VeSsHQ6C1X8t6pio084P7SHZYPJaaWJy0
          jg8pxCBjdMg24tRW8xSOVSDRfazVBM82Y0tCiQeEgBtLfjiIC93umOy8uI3TiEFkBC6vyj
          +LW7XnvpZUZRmKUGvExd8uMzYFrc+eUoiVnGoTWkTNv8GNdWV4AJU3tH1/LVbaM8kP0OHE
          BFhn+RRoEJJo4kjU9ozoXXMLKFoez4JBrcRRXmjACTgYHsawsmI9Ncv39TL+YUrMgawaxZ
          4UtCTrpcRQRPMyQwhiOoez6x3SEilcYwipDw7wjeTRa5K0M8UNjjcDDWgBlEDiz/DSlX2e
          2QwHy6sfhGNw+IReP6Fho9E5j9tL9Qf4FUVfAxyCB+JXoUzmhgcLaXTxaxxuO3jvaO9mQl
          BNIaKoJG2zm3Zh0e9TUpOcLF/a+hycU4uNN2udyKGyNQDULcLNcFL1eALogUpJ68e3Y9Lv
          taN/O13+w7LcHv/RtcAvNWGT8LymW8v75xppIang2Qg/ceBUNhLMg+n7R0H/yOtP02mnuv
          U7ZUUzPrOxWq65m5F5YpM7m33sHVox869iYmk1W3OAI1KxgexSQLVyWkcf2jOLd9Kn9pVk
          24+cemLhUImo2PJZ8VmuBqK6tVUm1cd4DDGYFNRhfQdg3XW1LuDGCuX9lKPgcUTAN9eUSP
          fczwWwauDYdEiPQZgMJgaUtzn2XwItZhsnNOqAapfDnF1himrWLNDf10/9No7y7+/TPP98
          wHZXmEvuGvUvMfbLqljB5fj4J0jyqykf3kZ1gObAwCD+sVQaMG5naI5TN5H4CMn+QdXxBV
          zxY2c11s9J2xi2v2dKI3bXffshwaWvIWYGBtBTxs9euFZdYtUKOUWPClYQPTA3uzbN1Kl5
          vYOfyS8E815HpJDxqUwbeHbzkMEr8DxrFE9aFOQAZv7USYqi0KPm/hOBC+LlR2mu0kDwB1
          DXt299TkAqXWaGrkXBHSHs0GCdsVtzS2axti/hrve5vdOzJw+k4gBDN91wdW8PU0G+bGLB
          DMRJXcHXa+KqjyDmakUHORNeylxxV+zDM6SFOXZzEzb7mTSm3Sihv4fzkjx/hSLVlf6o79
          3yXDAa0WDClhdym/71lIphdwc=
          -----END RSA PRIVATE KEY-----
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:9.6-alpine
